global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'roll_video'
    static_configs:
      - targets: ['localhost:9000']

  - job_name: 'celery'
    static_configs:
      - targets: ['localhost:5555']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:3306']