name: roll-video Docker Build and Push

on:
  push:
    paths:
      - '.github/workflows/roll-video-build.yml'
      - 'app/services/roll_video/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.repository == 'duanfuxing/RollVideo' }}
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Clean up disk space to avoid "No space left on device" errors
      - name: Clean up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          df -h

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Step 5: Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: app/services/roll_video
          file: app/services/roll_video/Dockerfile
          push: true
          tags: |
            catchoco/roll-video:supervisor
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      # Step 7: Move cache for next builds
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      # Step 8: Debug Disk Usage (Optional)
      - name: Check disk usage
        if: failure()
        run: |
          df -h
          du -sh /tmp/*
